### ISSUE TITLE
Cart item merging issues with editable cart items

### ISSUE THREAD

**Issue by willgorham** [somewherewarm/woocommerce-subscribe-all-the-things#196]
WP 4.8.1
WC 3.1.2
WCS 2.2.11
WC SATT RC-2.0
Storefront 2.2.5
No other plugins active

Steps to reproduce:
1. Create a product with at least one subscription scheme
2. Add product to cart - selecting a scheme or 'None' doesn't seem to matter
3. Go to the Cart. Change the subscription scheme on this product to something different. Click 'Update Cart'
4. Go back to the same single product page from step 2. Again add the product to the cart using the **same** scheme (or 'None') from step 2.
5. The quantity of the existing line item in the cart (with the updated scheme) will be incremented, instead of adding a new line item with the appropriate scheme

Note: Adding the product to the cart again using the **updated** scheme from step 3 above results in a new line item, instead of incrementing the line updated in step 3

**Comment by franticpsyx** [comment]
@willgorham thanks for this!

This one is a real issue but it look like a can of worms that I'd rather not open.

There's also the opposite/dual problem:

- Add to cart with scheme A.
- Change to scheme B.
- Add to cart again with scheme B selected.
- No merging happens.

WooCommerce generates a cart key the **first time** that a cart item is created. Any implementation of cart item data editing is doomed to suffer such issues unless it re-generates the cart key, as well.

However, third party code is very likely to depend on the initially generated cart key, so being too liberal with modifying cart keys can potentially break a number of things. Additionally, even if cart item key modification was acceptable, we still would need to address the challenge of clashes with existing keys.

If we abandon the idea of modifying the cart key, then we still have the same 2 problems to solve:

1. Fix incorrectly un-merged cart items on add-to-cart, which would need to rely on storing key hashes for modified cart items somewhere (e.g. item gets modified, we re-calculate is hash and store it, then when a new item with the same configuration (same hash as the one we stored) gets added to the cart we delete it and increment the qty of the existing one).
2. Prevent incorrect merging of cart items with the same hash, which is not possible without a `WC_Cart::find_product_in_cart` filter or a re-write of core logic, as far as I can see.

Hopefully I am not overcomplicating this but it looks like one of those tough-to-accept "won't fix" cases.

@thenbrent this is interesting to look at if you are into self-reference, like paintings of hands painting themselves. Or indexes things that shouldn't be indexed as indexed.

**Comment by franticpsyx** [comment]
@willgorham labelled this as "wontfix" for now but if you think there is a safe, reasonably short solution feel free to submit a PR.

**Comment by willgorham** [comment]
@franticpsyx I had a hunch that this would be a bit of a black hole - and could hinge on making core WooCommerce changes. I might dive in and see if I can come up with a solution, but your understanding of the complexity is right where I see it as well. Thanks for taking a look!

**Comment by franticpsyx** [comment]
This bugs me. Thought I'd throw this thought into the abyss of the inter-web.

**Comment by willgorham** [comment]
@franticpsyx Hah 😄, yeah this is a yucky one.

**Comment by moburkhardt** [comment]
I've observed that if products are subscription as well as regular products the "default" option will be added to the cart. E.g. if I add subscription "every 2 weeks" to the cart but the product defaults to a single purchase it will be added to the cart as "single purchase" not the subscription.

**Comment by franticpsyx** [comment]
Moved to the [APFS](https://github.com/somewherewarm/woocommerce-subscribe-all-the-things/issues/436) repository.
