### ISSUE TITLE
WCS Feature Parity Milestone 1b: Sign-up Fees

### ISSUE THREAD

**Issue by franticpsyx** [somewherewarm/woocommerce-subscribe-all-the-things#224]
From https://github.com/Prospress/woocommerce-subscribe-all-the-things/wiki/Roadmap

**Comment by Key7i** [comment]
Would love to see this Sign-up fees feature.

**Comment by franticpsyx** [comment]
@0dp 

👍 

Jumping straight to the nitty-gritty -- it should be relatively straightforward, but there's always a good chance we might run into issues/conflicts that may take a while to discover, as we have no acceptance/e2e tests here. I expect that existing SATT features could/will be affected by introducing sign-up fees and/or free trials.

Sign-up fees should be generally safer.

Parts of the code you'll want to start fiddling with:

* https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/class-wcs-att-product.php#L27
* https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/product/class-wcs-att-product-schemes.php#L362
* https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/class-wcs-att-scheme.php#L21 (there's no getter/setter there)
* https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/product/class-wcs-att-product-prices.php#L21 (no sign-up fees support there, not sure if it's needed at this point)
* https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/admin/meta-boxes/class-wcs-att-meta-box-product-data.php#L225 (add sign-up fee input)

I'm sure I'm missing a lot at this point, but if you decide to dig deeper please keep in mind that we'll need all existing features in SATT to be tested with/without Sign-Up fees, namely:

- subscribe to cart (no sign-up fee there?)
- synced vs un-synced schemes;
- add product to subscription (how should sign-up fees be treated there?)
- add cart to subscription (same as above)

There are lots of questions to ask here, and any PR that fails to answer these in detail wouldn't be considered for merging.

We'll need proof that the new feature works in all existing features/flows that SATT introduces/supports, or a detailed description of the limitations/debt.

Even if we did have acceptance tests covering all features/flows, we'd need to update them to take sign-up fees into account and test against the expected behavior.

But to do that, we'll need to define what's "expected" in each case, and that requires a fair amount of work in addition to getting Sign-Up fees to work in a baseline test case.

**Comment by 0dp** [comment]
Thanks for all the info.

For now I will fork the repo, and work on this feature. If I have any questions I'll get back on this thread. When I have some results, I will get back for advice on how to proceed.

🙏

**Comment by glagonikas** [comment]
Would this issue also allow us to add sign-up fees per component for Composite Products?

We would like to offer Composite Products with free trial and some optional components with individual sign-up fees.

If the customer signs up with no optional components, we'd give them the free trial, but if they pick some optional ones (that cost us money) we'd like to charge a sign-up fee (different for each component chosen).

Not sure if this can be achieved in another way, possibly with subscribe to cart (which we don't use) or it's an upcoming feature for Composite Products?

**Comment by franticpsyx** [comment]
Hey @glagonikas 

> Would this issue also allow us to add sign-up fees per component for Composite Products?

The integration between SATT and CP (or PB) is based on the premise that the entire collection will have subscription plans at "kit/bundle-level" only.

There is no plan to introduce Subscription Plans at Component level.

**Comment by franticpsyx** [comment]
Moved to the [APFS](https://github.com/somewherewarm/woocommerce-subscribe-all-the-things/issues/436) repository.
