### ISSUE TITLE
WCS Feature Parity: Limit Subscriptions

### ISSUE THREAD

**Issue by cturnbull** [somewherewarm/woocommerce-subscribe-all-the-things#299]
I saw this was mentioned in #1 but unless I've missed it, [Limit subscriptions](https://docs.woocommerce.com/document/subscriptions/store-manager-guide/#limit-subscription) has managed to avoid it's own feature request. Thanks

**Comment by franticpsyx** [comment]
@cturnbull Good point, we'll keep this open and add it to the roadmap, as well!

**Comment by franticpsyx** [comment]
Moved to the [APFS](https://github.com/somewherewarm/woocommerce-subscribe-all-the-things/issues/436) repository.
