### ISSUE TITLE
Allow multiple schemes with different sync dates to co-exist

### ISSUE THREAD

**Issue by mazgor** [somewherewarm/woocommerce-subscribe-all-the-things#359]
I just realized, that I can't add two weekly subscription options to a product. As it makes sense, that this doesn't work for subscriptions with no synchronization it would be great to allow this for subscriptions with synchronized payments. Because than, I can offer a weekly subscription for e.g. milk for all weekdays Monday through to Sunday and not only one day per week. And a customer can have maybe also two weekly subscriptions for the same product but for different days. I would use this together with this plugin (https://github.com/Prospress/woocommerce-subscriptions-preserve-billing-schedule), because of course it only makes sense, if the schedule is preserved... best regards!

**Comment by thenbrent** [comment]
Hi @mazgor, that's a good idea. It will certainly make sense with sync'd dates.

You can create more than one _weekly_ scheme already, but the billing scheduled can't be identical, for example:

* two weekly schemes with different length: http://pic.pros.pr/ad8e2a493f3c
* displays like this: http://pic.pros.pr/48ce54a144b9

**Comment by mazgor** [comment]
Hi @thenbrent, thank you for your reply. Ok, but maybe you could change it in a way that it also works for subscriptions that never expire? Now on my test-site it displays like [this](https://www.dropbox.com/s/g53c8b1okiy4ay5/Bildschirmfoto%202018-10-12%20um%2014.06.03.png?dl=0) and it would be great, if the customer could chose the days from Monday to Sunday and all with open end, never expiring. Thank you!

**Comment by franticpsyx** [comment]
Makes sense @mazgor !

@thenbrent I believe this is due to a limitation in how scheme keys are generated, which didn't take syncing into account.

It should be fairly straightforward to allow this by generating unique scheme keys, but I could be missing something major that might be blocking this.

One thing I'm concerned about is that scheme keys are stored as order item meta, so we'll need some extra logic to ensure everything is bw compatible.

**Comment by franticpsyx** [comment]
> also works for subscriptions that never expire

Length is included in the key and shouldn't be a problem once this is implemented -- see https://github.com/Prospress/woocommerce-subscribe-all-the-things/blob/master/includes/class-wcs-att-scheme.php#L106

**Comment by franticpsyx** [comment]
Moved to the [APFS](https://github.com/somewherewarm/woocommerce-subscribe-all-the-things/issues/436) repository.
