### ISSUE TITLE
NYP Compatibility

### ISSUE THREAD

**Issue by helgatheviking** [somewherewarm/woocommerce-subscribe-all-the-things#371]
- [x] If a variable product has an NYP variation, then the SATT options do not display: This is because NYP also filters `woocommerce_available_variation` to change the `price_html` [here]. [Propose adding SATT as different key](ab3709090b7e6774b59a30eca0ea92766675a956)
- [x] If no suggested price (the price string ends up null) the subscription terms for a scheme are blank. [Propose filtering args](0d9a275f4e04b5e89fd566068ac427c69d3772b7)

Once you get both to display you SATT options and NYP price input to display you still have two issues:
- [x] Scheme Discount is applied to NYP price. If you enter $1234 as the price is $1110 in the cart with a 10% discount. For NYP, 
- [x] SATT options appear before NYP input. 
- [x] If suggested price exists, then it shows up in the SATT options

**SATT Options Do Not Display**
![image](https://user-images.githubusercontent.com/507025/47361979-f3e45280-d698-11e8-839a-0f4f1261bbfa.png)

**If price string is null (ie: no suggested price for NYP), terms do not display**
![image](https://user-images.githubusercontent.com/507025/47362420-f7c4a480-d699-11e8-8cf1-429c7e09eff1.png)

**Suggested price string in the SATT options**
![image](https://user-images.githubusercontent.com/507025/47364995-3bbaa800-d6a0-11e8-9e50-53bbd297e132.png)

**Comment by helgatheviking** [comment]
This 6f0a2dfacf416359795dd68f5c52224b15479e5a sorts out the display order. While 0d9a275f4e04b5e89fd566068ac427c69d3772b7 with the compat code below (needs a `class_exists` wrapper or something, but this was just a quick test) sorts out the discount and price string parts.

```
// Don't display price string in option if NYP.
function kia_satt_subs_args( $args, $scheme, $product ) {
	if( WC_Name_Your_Price_Helpers::is_nyp( $product ) ) {
		$args['subscription_price'] = false;
		$args['product_price'] = false;
	}
	return $args;
}
add_filter( 'wcsatt_subscription_price_html_args', 'kia_satt_subs_args', 10, 3 );

// No discount for NYP subscriptions. 
function kia_no_discount_for_nyp( $schemes, $product ) {
	if( WC_Name_Your_Price_Helpers::is_nyp( $product ) ) {
		foreach( $schemes as $scheme ) {
			$scheme->set_discount( 0 );
		}
	}
	return $schemes;
}
add_filter( 'wcsatt_product_subscription_schemes', 'kia_no_discount_for_nyp', 10, 2 );
```

Result:

![image](https://user-images.githubusercontent.com/507025/47391803-662c5580-d6e0-11e8-80eb-4f17fe676a89.png)

For some reason I really struggled to find the point in the code where you are applying the discount. But, I did find that I can dynamically kill the discount via `wcsatt_product_subscription_schemes`. Is there a better way to do this?

**Comment by franticpsyx** [comment]
@helgatheviking would `wcsatt_price_filters_allowed` perhaps help here?

**Comment by helgatheviking** [comment]
Maybe! Does that exist or something to add? Afk most of the morning.

**Comment by helgatheviking** [comment]
Found the `wcsatt_price_filters_allowed` filter and YAS! Sending the PR as I _think_ it's working well now:

```
function kia_satt_subs_args( $args, $scheme, $product ) {
	if( WC_Name_Your_Price_Helpers::is_nyp( $product ) ) {
		$args['subscription_price'] = false;
		$args['product_price'] = false;
	}
	return $args;
}
add_filter( 'wcsatt_subscription_price_html_args', 'kia_satt_subs_args', 10, 3 );


function kia_no_discount_for_nyp( $discount_allowed, $product ) {
	if( WC_Name_Your_Price_Helpers::is_nyp( $product ) ) {
		$discount_allowed = false;
	}
	return $discount_allowed;
}
add_filter( 'wcsatt_price_filters_allowed', 'kia_no_discount_for_nyp', 10, 2 );
```

**Comment by franticpsyx** [comment]
Moved to the [APFS](https://github.com/somewherewarm/woocommerce-subscribe-all-the-things/issues/436) repository.
