### ISSUE TITLE
SATT not showing when CART and CHECKOUT on same page

### ISSUE THREAD

**Issue by pprotschka** [somewherewarm/woocommerce-subscribe-all-the-things#402]
It appears that is more and more common that shop owners like to have the cart and checkout on the same page. Woocommerce has adjusted to this simply including the shortcodes on one page will generally work without issues.  tutorial example: [https://businessbloomer.com/woocommerce-cart-checkout-same-page/](url)

WSATT has issues with this because the hook 
**add_action( 'woocommerce_before_cart_totals', array( __CLASS__, 'show_cart_subscription_options' ) );**
will not fire if both woocommerce shortcodes are on the same page because woocommerce_cart_totals is not called in this case.

a simple solution is to remove the original hook and rehook to woocommerce_cart_collaterals however this needs some addtional styling.

A feature request would be to enable Cart and Checkout on the same Page without user having to modify or style any hooks.

my solution to this:
```php
<?php 

add_action('wp_head', 'change_satt_cart_options_location');

function change_satt_cart_options_location() {

   remove_action('woocommerce_before_cart_totals', array('WCS_ATT_Display_Cart', 'show_cart_subscription_options'));
   add_action('woocommerce_cart_collaterals', array('WCS_ATT_Display_Cart', 'show_cart_subscription_options'), 5);
} ?>`

**Comment by franticpsyx** [comment]
Hey @pprotschka 

Thanks for sharing this workaround with us! This modification appears to move the cart-subscription options to the cart-collaterals section. While I can definitely see how this would help in your specific case, it's not clear to me why a theme/plugin would not fire the `woocommerce_before_cart_totals` action.

**Comment by pprotschka** [comment]
@franticpsyx 

because in order to prevent duplicate cart totals showing the hook is removed by WC itself when cart and checkout are on the same page.

from: wc-template-functions.php  @line 1534

`<?php
if ( ! function_exists( 'woocommerce_cart_totals' ) ) {
    function woocommerce_cart_totals() {
        if ( is_checkout() ) {
            return;
        }
        wc_get_template( 'cart/cart-totals.php' );
    }
}
?>`

so this hook is never called when CART and CHECKOUT are on the same page because cart-totals.php is never rendered.

**Comment by franticpsyx** [comment]
@pprotschka oh that's interesting, thanks for making it clear!

Did everything work flawlessly for you after adding that snippet? Any styling-related implications?
