### ISSUE TITLE
Product Bundles & Subscriptions - Display Item Grouping "None" Doesn't Work when "Add to Subscription" Used

### ISSUE THREAD

**Issue by robin-scott** [somewherewarm/woocommerce-subscribe-all-the-things#405]
Really specific case here.

Using Bundles to subscribe to products-as-subscriptions, with the product grouping set to none. 

Display in My Account as this:

![image](https://user-images.githubusercontent.com/17259256/50923769-b5636600-1445-11e9-9d79-4b561b22fc81.png)

Good - this is as expected and wanted.

Visit same bundle product, and "add to subscription" and this displays like so:

![image](https://user-images.githubusercontent.com/17259256/50923912-fbb8c500-1445-11e9-9e82-07449a1870ed.png)

Bundle product is setup thus:

![image](https://user-images.githubusercontent.com/17259256/50923968-1ee37480-1446-11e9-9d95-fc002ffdb546.png)

Replicated this on a couple of installs. 

Ideally the add to subscription products would display as the original purchased items (which are just right!).

**Comment by robin-scott** [comment]
There's also a side issue, which is, the newly added items if they are the same product, should increment the quantity by 1, as opposed to displaying again, though I appreciate there's some complexity living here.

**Comment by robin-scott** [comment]
This also occurs if the display selected is "flat" rather than "none" - the "add to subscription" bundle items will always display as "grouped".

**Comment by franticpsyx** [comment]
Moved to the [APFS](https://github.com/somewherewarm/woocommerce-subscribe-all-the-things/issues/436) repository.
