### ISSUE TITLE
Compatible with API Manager Extension?

### ISSUE THREAD

**Issue by codeclinic** [somewherewarm/woocommerce-subscribe-all-the-things#422]
Is this compatible with the API Manager Extension available from the WooCommerce store?

I'm using SATT to create bundled subscriptions of software, and I need to be able to switch on/off the API key when a subscription expires & on again when a subscription is renewed / continued.

Will SATT do this, as the normal subscription product type does?

Thanks, for the great work. I'd been looking for days to get the functionality that SATT offers.

**Comment by franticpsyx** [comment]
Hey @codeclinic -- thanks for the feedback 👍 

> Will SATT do this, as the normal subscription product type does

The API Manager extension is not officially supported by SATT, and we have no plans to work on new integrations within the next couple months or so. At the moment, the project is in code-freeze mode, as we are working to release SATT through WooCommerce.com.

> I need to be able to switch on/off the API key when a subscription expires & on again when a subscription is renewed / continued.

Did you already try this? Any results to share? Your help would be deeply appreciated here, as it might take a while before a new SATT release cycle starts.
