### ISSUE TITLE
SATT calculates discounts for Bundles in Composite products incorrectly

### ISSUE THREAD

**Issue by eflyerman** [somewherewarm/woocommerce-subscribe-all-the-things#431]
I created a Composite Product with multiple Product Bundles that contains individually priced items.  The SATT subscription price should be based upon a discount percent applied from the subscription.

The resulting price of the subscription is incorrect.  It is calculating **A** discount but the result is incorrect. I can't derive the function that is being applied.  The Bundle price may not be available at the time of calculation.

eflyerman

**Comment by franticpsyx** [comment]
Moved to the [APFS](https://github.com/somewherewarm/woocommerce-subscribe-all-the-things/issues/436) repository.
